### ISSUE TITLE
How to debug envman?

### ISSUE THREAD

**Issue by autonomousapps** [bitrise-io/envman#184]
Somewhat similar to this issue https://github.com/bitrise-io/envman/issues/175

My build is failing at the github-release stage, and it seems like it's happening because an env var I add on a prior step is not being picked up at this step. I'd like to be able to debug somehow to see what the value is at the step it's created and the step it's consumed by.

I tried using `echo "${MY_VAR}"`, but it didn't do anything. Which I guess either means MY_VAR is empty or something else is wrong.

**Comment by Roland-Bak** [comment]
Hello there @autonomousapps !

Could you please provide the URL of the related build and also enable Support Access on the Settings tab of the app ( https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/ ) so that we can take a more in-depth look?
I'd be happy to like to check some configs, and maybe do a few test to see how this could be fixed :)

**Comment by autonomousapps** [comment]
Thanks for the reply. I was able to resolve my issue, although tbh I don't recall how :-/ If it comes up again, I'll try to drop you a note. Feel free to close this issue.

**Comment by rachid-debu** [comment]
Hello there

I have the same issue : 
`envman add --key BIT_NODE_ENV --value "production"`
`echo "Output BIT_NODE_ENV=${BIT_NODE_ENV}`

Results to : 
`Output BIT_NODE_ENV=`

Link to my build : https://app.bitrise.io/build/1717dca025d9baad#?tab=log (enabled support)

**Comment by bitce** [comment]
Hi @rachid-debu!

This is happening because the CLI reads variables at the beginning of steps. This means the variable you define in a Script step will not be available within that same script, only in the steps that follow that script.
